name: Code check

on:
    # Trigger the workflow on push or pull request,
    # but only for some branches
    push:
        branches:
            - master
            - plugin
    pull_request:
        branches:
            - master
            - plugin

jobs:
    run-linters:
        name: Run linters and TS checks
        runs-on: ubuntu-latest

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            # ESLint and Prettier must be in `package.json`
            - name: Install Node.js dependencies
              run: npm i

            - name: Link starknet-hardhat-plugin to example repo
              run: npm run link-plugin

            - name: Run TypeScript correctness
              run: npx tsc --noEmit

            - name: Check for executables
              run: npm run check-executable

            - name: Check all tests are executed
              run: npm run check-all-tests

            - name: check for hardhat config type correctness
              run: npm run check-config-file

            - name: Run linter
              run: npm run lint

            - name: Run format check
              run: npm run format-check
